<a href="https://colab.research.google.com/github/janko0823/2020-2-AI/blob/master/code/02_tf_interm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



텐서플로



In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
tf.executing_eagerly()

True

In [ ]:
a = tf.constant([[1, 2],
                [3, 4]])
print(a)
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [ ]:
x = [[2.]]
m = tf.matmul(x, x)
print(m)
print(m.numpy())

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
[[4.]]


In [ ]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[2., 0.], [1., 2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]


In [ ]:
gop = tf.matmul(matrix2, matrix1)
print(gop.numpy())

[[ 2.  4.]
 [ 7. 10.]]


브로드 캐스팅 지원

In [ ]:
a = tf.constant([[1, 2],
                [3, 4]])
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
x = tf.constant([[0], [10], [20], [30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3, 3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf. int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print((x+y).numpy())

x = tf.constant((np.ones((3, 3))))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

x = tf.constant((np.arange(3).reshape(3, 1)))
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np

c = np.multiply(a, b)
print(c)

In [ ]:
a = 2
b = 3
c = tf.add(a, b)
print(c.numpy())

In [ ]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
pow_op = tf.pow(add_op, mul_op)

print(pow_op.numpy())

In [ ]:
tf.pow(5, 6)

In [ ]:
a = tf.constant(2.)
b = tf.constant(3.)
c = tf.constant(5.)

mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print("mean = ", mean.numpy())
print("sum = ", sum.numpy())

mean =  3.3333333
sum =  10.0


행렬, 원소와의 곱

In [ ]:
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [ ]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.add(a, 1)

In [ ]:
print(a)
print(a.numpy())
print(b)
print("asdf", b.numpy())
print(a * b)

rank

In [ ]:
my_image = tf.zeros([2, 5, 5, 3])
my_image.shape

In [ ]:
tf.rank(my_image)

shape와 reshape

In [ ]:
rank_three_tensor = tf.ones([3, 4, 5])
rank_three_tensor.shape

In [ ]:
rank_three_tensor.numpy()

In [ ]:
matrix = tf.reshape(rank_three_tensor, [6, 10])
matrix

In [ ]:
matrixB = tf.reshape(matrix, [3, -1])
matrixB

In [ ]:
matrixAlt = tf.reshape(matrixB, [4, 3, -1])
matrixAlt

In [ ]:
float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)
float_tensor

In [ ]:
float_tensor.dtype

변수 Variable

In [ ]:
v = tf.Variable(0, 0)
v

In [ ]:
w = v + 10
w

In [ ]:
w.numpy()

In [ ]:
v = tf.Variable(2, 0)
v.assign_add(5)
v

In [ ]:
v.read_value()